services:
  app:
    # カレントディレクトリのDockerfileを使ってビルド
    build: .
    
    # シェルを起動し続けるための設定（これがないとすぐ終了します）
    tty: true
    stdin_open: true
    
    # ホストのファイルをコンテナ内で編集したい場合のマウント設定
    volumes:
      - ./src:/src
    
    # コンテナログイン時の初期ディレクトリ
    working_dir: /src